### ISSUE TITLE
Create Javascript HomeAssistant API

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/hacontrolpoint#2]
The basics are in haproxy.php and js/my-app.js but it's mostly hard-coded to my specific installation.

Need a javascript API that will populate javascript objects with the entities and states pulled from HASS. Would be nice to tie it to HTML elements via a data-entity attribute, and have it automatically update those HTML elements when it refreshes its data from HASS.

**Comment by michaelarnauts** [comment]
I'm working on this.

**Comment by michaelarnauts** [comment]
An API that includes all this is commited in babe221af89d1ddfe2480d05895802a0a6e0a269.
