### ISSUE TITLE
JavaScript API - Auto update HTML fields based on data-entity value

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/hacontrolpoint#4]
If we give HTML elements a data-entity attribute (ex: <div class="light" data-entity="light.porch">) it should automatically update the div with the state of the light.porch entity when it is updated from HASS

**Comment by michaelarnauts** [comment]
Ideally, it should tap into the eventstream to update the entities in real time.

**Comment by cgarwood** [comment]
Real time updates would be awesome compared to polling for updates.

**Comment by michaelarnauts** [comment]
This is implemented in my branch.

**Comment by michaelarnauts** [comment]
Fixed in babe221af89d1ddfe2480d05895802a0a6e0a269
